### ISSUE TITLE
Asteroid aborts: Assertion `newScore > _lastScore' failed

### ISSUE THREAD

**Issue by LPDagallier** [BenoitMorel/Asteroid#7]
Hi,

I'm facing an error when running Asteroid with multi-copy gene trees.

For example, running: 
asteroid -i test.trees -p asteroid_test -b 100 > asteroid.log
I get the following error:
"asteroid: /home/chrisribe/b/code/asteroid/src/core/DistanceMethods/AsteroidOptimizer.cpp:146: bool AsteroidOptimizer::computeAndApplyBestSPR(): Assertion `newScore > _lastScore' failed.
Aborted (core dumped)"

In this case I don't use a mapping file because I renamed all the sequences names so that sequences from a same species have the same name.
Asteroid is running on a cluster.

The test dataset and logfile are attached.
[test.trees.txt](https://github.com/BenoitMorel/Asteroid/files/11984789/test.trees.txt)
[asteroid.log](https://github.com/BenoitMorel/Asteroid/files/11984784/asteroid.log)

**Comment by BenoitMorel** [comment]
Hi Léo-Paul,

Thanks a lot for the report. I also reproduce on my laptop. I think it's
because you are not using a mapping file despite having multi-copy families
(it's a bit hidden in the documentation, but see
https://github.com/BenoitMorel/Asteroid#mapping-file).  Basically, Asteroid
can't read trees with duplicated names.

Sorry, I should have added a check to detect this and report an explicit
error. Also, now that I think about it, I could also support what you are
doing (duplicated names that represent the same species). I'll try to do it
next week, so if you are not in a hurry, you can also wait for my update.

Have a nice week-end,
Benoit

**Comment by BenoitMorel** [comment]
Hi Léo-Paul,
If you update Asteroid (from the repository: git pull && ./install.sh),
your run should now work. Let me know if not :)
Best,
Benoit

**Comment by LPDagallier** [comment]
Hi Benoit,
Oh that is great ! Thanks a lot for implementing this feature so fast.
I'll try on my side and let you know.
Best,
Léo-Paul

**Comment by LPDagallier** [comment]
It works perfectly, thanks a lot Benoit !
